sudo: true
language: python
matrix:
  include:
  - python: 3.6
    env: TOX_ENV=py36
  - python: 3.8
    env: TOX_ENV=py38
  - python: 3.8
    env: TOX_ENV=lint
before_install:
- sudo apt-get -y install libvirt-dev
- python -m pip install --upgrade pip
install: pip3 --use-feature=2020-resolver install tox
script: tox -c tox.ini-travis -e $TOX_ENV
